### ISSUE TITLE
OSF rate limiting

### ISSUE THREAD

**Issue by AartGoossens** [GoldenCheetah/OpenData#4]
I'm regularly bumping into `429 RuntimeErrors` when downloading data. [Apparently](https://developer.osf.io/#tag/Errors-and-Error-Codes) access to OSF is rate limited:

> Authenticated requests have a rate limit of 10,000/day.
> Unauthenticated requests have a rate limit of 100/hour.

How I make use of authenticated requests? It appears that having an account at osf.io is not enough. Do I need to fork the project or request access to the project to be able to make use of the higher authenticated rate limit?

**Comment by liversedge** [comment]
Are you using a personal access token ?
https://developer.osf.io/#tag/General-Usage

**Comment by AartGoossens** [comment]
> Are you using a personal access token ?

I didn't try that before (did use username+password) but I still get the 429's with the token now.
I suspect I need to have access to the OpenData project on OSF to be able to make use of the _authenticated rate limits_.

**Comment by liversedge** [comment]
Its open, so access is public!
Do you need to apply for access!?

**Comment by AartGoossens** [comment]
Yes, access is public of course, but it might be rate limited according to the **unauthenticated** rate limit. The question is how I can use the **authenticated** rate limit...

**Comment by AartGoossens** [comment]
To be clear: it does work from time to time, just not **all** the time. And tonight apparently some other people are downloading a lot of files too so I keep hitting the rate limit...

**Comment by AartGoossens** [comment]
Closing this issue as it is resolved by moving (well, actually copying) the data to AWS S3.
